In [1]:
!pip install numpy


mambajs 0.19.13

Process pip requirements ...

Requirement numpy already handled by conda/micromamba/mamba.


In [2]:
import numpy as np
import time

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

(2, 3)
2
int32


In [15]:
py_list = list(range(1_000_000))
py_res = []
start_time = time.time()
for i in py_list:
    py_res.append(i+5)
end_time = time.time()
print("python list time: ", end_time - start_time)

python list time:  0.3970000743865967


In [16]:
np_arr = np.arange(1_000_000)
start_time = time.time()
np_res = np_arr + 5
end_time = time.time()
print("pnumpy list time: ", end_time - start_time)

pnumpy list time:  0.006999969482421875


In [17]:
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [19]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [21]:
print(np.full((2,3),7))

[[7 7 7]
 [7 7 7]]


In [24]:
print(np.arange(0,10,2))

[0 2 4 6 8]


In [26]:
print(np.linspace(0, 1, 5))

[0.   0.25 0.5  0.75 1.  ]


In [28]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
print(np.diag([1, 2, 3]))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [36]:
np.array([1, 2, 3], dtype = float)

array([1., 2., 3.])

In [37]:
arr = np.array([1.5, 2.7, 3.9])
print (arr.astype(int))

[1 2 3]


In [39]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

In [41]:
print(arr[0,1]) # first row second col
print(arr[1,2]) # second row tird col
print(arr[2,0]) # third row first col

20
60
70


In [42]:
print(arr[-1,-2]) # last row sec last col
print(arr[-2,-3]) # sec last row first col
print(arr[-3,-1]) # first row last col

80
40
30


In [43]:
# General form : arr[start:stop:step]
print(arr[0:2, 1:3]) #rws o-1, col 1-2

[[20 30]
 [50 60]]


In [44]:
print(arr[0:2, 0:2]) #rws o-1, col 0-1

[[10 20]
 [40 50]]


In [45]:
#jump of two rows and two cols
#will print first element in first row and jump to 3rd row first col
# then will jump to third row first element and then to last lement last row
print(arr[::2, ::2])

[[10 30]
 [70 90]]


In [55]:
slice_arr = arr[0, :2]
slice_arr[0] = 999
print(arr[0])

[999  20  30]


In [57]:
copy_arr = arr[1].copy()
copy_arr[1] = 555
print(arr[1])

[40 50 60]


In [12]:
rng = np.random.default_rng()
flips = rng.integers(0, 2, size = 100000)
prob_heads = np.mean(flips)
print("Estimated Proability of heads is:",prob_heads)

Estimated Proability of heads is: 0.50083


In [11]:
rng = np.random.default_rng(seed=40)
flips = rng.integers(0, 2, size = 100)
prob_heads = np.mean(flips)
print(flips)
print("Estimated Proability of heads is:",prob_heads)

[1 1 0 1 0 1 0 0 0 1 0 1 1 0 0 0 1 1 1 1 1 0 1 0 0 1 0 0 1 0 1 0 1 0 0 1 0
 1 0 0 1 0 0 0 0 1 0 1 1 0 1 0 1 0 1 0 0 1 0 0 1 0 1 1 1 0 1 0 1 0 0 0 1 0
 0 0 1 1 0 0 1 1 1 0 1 0 0 0 0 0 1 0 1 0 0 1 1 1 0 0]
Estimated Proability of heads is: 0.45


In [15]:
#python loop
start = time.time()
squares = [i**2 for i in range(1000000)]
end = time.time()
print("Loop time:",end - start)

#vectorized numpy
sta_t = time.time()
arr = np.arange(1000000)
sqr_np = arr**2
end_T = time.time()
print("Vectorized Time:", end_T - sta_t)

Loop time: 0.22300004959106445
Vectorized Time: 0.003999948501586914
